version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - mynetwork

  node:
    build: 
      context: node
    container_name: node
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    command: ["dockerize", "-wait", "tcp://db:3306", "node", "index.js"]
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - /home/raul/fullcyclenginxnode/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
